# Generated by Django 4.1.7 on 2023-06-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='data',
            field=models.JSONField(),
        ),
    ]
